[project]
name = "uv2nix-template"
version = "0.1.0"
requires-python = "~=3.10"
dependencies = [
    "gymnasium==0.28.1",
    "jupyter>=1.1.1",
    "numpy~=1.0",
    "stable-baselines3==2.0.0",
    "torch>=2.5.1",
]
